// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5XFv8ksPRpW0Pt59yNzT7qxphJNo-5U',
    appId: '1:421320065355:web:f1882cbd04bf2fd20568ce',
    messagingSenderId: '421320065355',
    projectId: 'impact-nation-fund-raising',
    authDomain: 'impact-nation-fund-raising.firebaseapp.com',
    storageBucket: 'impact-nation-fund-raising.firebasestorage.app',
    measurementId: 'G-6F0DH7F8W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0kVpFCZ0_1TaIv2fWnnGNP8-6Ws5oV8',
    appId: '1:421320065355:android:cea48a52865179430568ce',
    messagingSenderId: '421320065355',
    projectId: 'impact-nation-fund-raising',
    storageBucket: 'impact-nation-fund-raising.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuvnBGAfmoM0-bXZTQnDFfOyAoE1Z3TsA',
    appId: '1:421320065355:ios:85412fa90c3d3bf60568ce',
    messagingSenderId: '421320065355',
    projectId: 'impact-nation-fund-raising',
    storageBucket: 'impact-nation-fund-raising.firebasestorage.app',
    iosClientId: '421320065355-6nb2d276rub0l3g6iej4fn0iam6pj01a.apps.googleusercontent.com',
    iosBundleId: 'com.example.impactNationFundRaising',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuvnBGAfmoM0-bXZTQnDFfOyAoE1Z3TsA',
    appId: '1:421320065355:ios:85412fa90c3d3bf60568ce',
    messagingSenderId: '421320065355',
    projectId: 'impact-nation-fund-raising',
    storageBucket: 'impact-nation-fund-raising.firebasestorage.app',
    iosClientId: '421320065355-6nb2d276rub0l3g6iej4fn0iam6pj01a.apps.googleusercontent.com',
    iosBundleId: 'com.example.impactNationFundRaising',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR5XFv8ksPRpW0Pt59yNzT7qxphJNo-5U',
    appId: '1:421320065355:web:4f7bfe9bcf62ff650568ce',
    messagingSenderId: '421320065355',
    projectId: 'impact-nation-fund-raising',
    authDomain: 'impact-nation-fund-raising.firebaseapp.com',
    storageBucket: 'impact-nation-fund-raising.firebasestorage.app',
    measurementId: 'G-GYR6V8C268',
  );
}
