import 'package:cloud_firestore/cloud_firestore.dart';
import '../domain/models/campaign.dart';

class CampaignRepository {
  final FirebaseFirestore _firestore;

  CampaignRepository({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  CollectionReference<Map<String, dynamic>> get _campaigns =>
      _firestore.collection('campaigns');

  /// Stream all campaigns ordered by creation date (newest first).
  Stream<List<Campaign>> watchAllCampaigns() {
    return _campaigns.orderBy('createdAt', descending: true).snapshots().map(
          (snapshot) => snapshot.docs
              .map((doc) => Campaign.fromMap(doc.data(), doc.id))
              .toList(),
        );
  }
  
  /// Stream the active campaign (assuming there's usually one main active one).
  Stream<Campaign?> watchActiveCampaign() {
    return _campaigns
        .where('status', isEqualTo: CampaignStatus.ACTIVE.name)
        .snapshots()
        .map((snapshot) {
      if (snapshot.docs.isEmpty) return null;
      
      // Sort in memory to avoid requiring a Firestore composite index
      final campaigns = snapshot.docs
          .map((doc) => Campaign.fromMap(doc.data(), doc.id))
          .toList();
          
      campaigns.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return campaigns.first;
    });
  }

  Future<void> createCampaign({
    required String name,
    required String description,
    required double targetAmount,
    required DateTime startDate,
    required DateTime endDate,
    CampaignStatus status = CampaignStatus.DRAFT,
  }) async {
    final now = DateTime.now();
    final campaign = Campaign(
      id: '', // Generated by Firestore
      name: name,
      description: description,
      targetAmount: targetAmount,
      startDate: startDate,
      endDate: endDate,
      status: status,
      createdAt: now,
      updatedAt: now,
    );

    await _campaigns.add(campaign.toMap());
  }

  Future<void> updateCampaign(Campaign campaign) async {
    final data = campaign
        .copyWith(updatedAt: DateTime.now())
        .toMap();
    await _campaigns.doc(campaign.id).update(data);
  }

  Future<void> deleteCampaign(String id) async {
    await _campaigns.doc(id).delete();
  }
}
